train:
  log_file: logs
  checkpoints: checkpoints

  image_size: 128
  num_attrs: 12
  pretrained: true
  model_path: ""
  save_enable: true

  tune:
    num_epoch: 15
    lr: 0.0005

  GPU:
    enable: true
    name: "cuda:6"

  data:
    batch_size: 32
    batch_size_valid: 16
    loader_jobs: 8
    base: "/root/data"
    images: "img_align_celeba/img_align_celeba"
    attrs: "list_attr_celeba.csv"
    attributes:
      - "Bangs"
      - "Black_Hair"
      - "Blond_Hair"
      - "Brown_Hair"
      - "Bushy_Eyebrows"
      - "Eyeglasses"
      - "Male"
      - "Mouth_Slightly_Open"
      - "Mustache"
      - "No_Beard"
      - "Pale_Skin"
      - "Young"

test:
  pretrained: true
  model_path: ""
  num_attrs: 12